import { ConflictException,Injectable,NotFoundException } from '@nestjs/common'
import { AssetHistoryAction,Prisma } from '@prisma/client'
import { PrismaService } from '../../database/prisma.service'
import { CreateAssetDto,ListAssetsQuery,UpdateAssetDto } from './assets.dto'
const include={category:true,model:true,manufacturer:true,status:true,assignedUser:true,department:true,location:true,warehouse:true} as const
@Injectable()
export class AssetsService {
  constructor(private readonly db:PrismaService){}
  async list(q:ListAssetsQuery){const where:Prisma.AssetWhereInput={deletedAt:null,categoryId:q.category,departmentId:q.department,locationId:q.location,status:q.status?{code:q.status}:undefined,assignedUserId:q.assignedUser,OR:q.search?[{assetTag:{contains:q.search,mode:'insensitive'}},{name:{contains:q.search,mode:'insensitive'}},{serialNumber:{contains:q.search,mode:'insensitive'}}]:undefined};const allowed=['assetTag','name','createdAt','updatedAt','purchaseCost'];const sort=allowed.includes(q.sort)?q.sort:'assetTag';const [data,total]=await this.db.$transaction([this.db.asset.findMany({where,include,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{[sort]:q.order}}),this.db.asset.count({where})]);return {data,meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}}}
  async get(id:string){const value=await this.db.asset.findFirst({where:{id,deletedAt:null},include});if(!value)throw new NotFoundException({code:'ASSET_NOT_FOUND',message:'Không tìm thấy tài sản'});return value}
  async summary(){const [total,assigned,available,attention]=await Promise.all([this.db.asset.count({where:{deletedAt:null}}),this.db.asset.count({where:{deletedAt:null,assignedUserId:{not:null}}}),this.db.asset.count({where:{deletedAt:null,status:{code:'READY'}}}),this.db.asset.count({where:{deletedAt:null,status:{code:{in:['MAINTENANCE','BROKEN','LOST']}}}})]);return {total,assigned,available,due:0,attention}}
  async history(id:string){await this.get(id);return {data:await this.db.assetHistory.findMany({where:{assetId:id},include:{actor:{select:{fullName:true}}},orderBy:{createdAt:'desc'}})}}
  async create(body:CreateAssetDto){try{return await this.db.$transaction(async tx=>{const {performedBy,...data}=body;const asset=await tx.asset.create({data:{...data,assetTag:data.assetTag.trim(),name:data.name.trim()},include});const actor=performedBy||(await tx.user.findFirst())?.id;if(actor)await tx.assetHistory.create({data:{assetId:asset.id,action:AssetHistoryAction.CREATED,description:'Tạo tài sản',performedBy:actor}});return asset})}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')throw new ConflictException({code:'ASSET_TAG_EXISTS',message:'Mã tài sản hoặc barcode đã tồn tại'});throw e}}
  async update(id:string,body:UpdateAssetDto){await this.get(id);const {performedBy,...data}=body;const normalized={...data,assetTag:data.assetTag?.trim(),name:data.name?.trim(),barcode:data.barcode?.trim(),serialNumber:data.serialNumber?.trim()};return this.db.$transaction(async tx=>{const asset=await tx.asset.update({where:{id},data:normalized,include});const actor=performedBy||(await tx.user.findFirst())?.id;if(actor)await tx.assetHistory.create({data:{assetId:id,action:AssetHistoryAction.UPDATED,description:'Cập nhật thông tin tài sản',performedBy:actor}});return asset})}
  async remove(id:string){await this.get(id);return this.db.$transaction(async tx=>{const actor=(await tx.user.findFirst())?.id;if(actor)await tx.assetHistory.create({data:{assetId:id,action:AssetHistoryAction.UPDATED,description:'Ngừng theo dõi tài sản (soft delete)',performedBy:actor}});await tx.asset.update({where:{id},data:{deletedAt:new Date()}});return {success:true}})}
}
